apiVersion: v1
kind: Service
metadata:
  name: drone-srvc
  labels:
    app: drone-srvc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: drone-server
  type: LoadBalancer
